Map<String, dynamic> modelInputTemplate = {
  'MS SubClass': null,
  'MS Zoning': null,
  'Lot Frontage': null,
  'Lot Area': null,
  'Street': null,
  'Lot Shape': null,
  'Land Contour': null,
  'Utilities': null,
  'Lot Config': null,
  'Land Slope': null,
  'Neighborhood': null,
  'Condition 1': null,
  'Condition 2': null,
  'Bldg Type': null,
  'House Style': null,
  'Overall Qual': null,
  'Overall Cond': null,
  'Year Built': null,
  'Year Remod/Add': null,
  'Roof Style': null,
  'Roof Matl': null,
  'Exterior 1st': null,
  'Exterior 2nd': null,
  'Mas Vnr Type': null,
  'Mas Vnr Area': null,
  'Exter Qual': null,
  'Exter Cond': null,
  'Foundation': null,
  'Bsmt Qual': null,
  'Bsmt Cond': null,
  'Bsmt Exposure': null,
  'BsmtFin Type 1': null,
  'BsmtFin SF 1': null,
  'BsmtFin Type 2': null,
  'BsmtFin SF 2': null,
  'Bsmt Unf SF': null,
  'Total Bsmt SF': null,
  'Heating': null,
  'Heating QC': null,
  'Central Air': null,
  'Electrical': null,
  '1st Flr SF': null,
  '2nd Flr SF': null,
  'Low Qual Fin SF': null,
  'Gr Liv Area': null,
  'Bsmt Full Bath': null,
  'Bsmt Half Bath': null,
  'Full Bath': null,
  'Half Bath': null,
  'Bedroom AbvGr': null,
  'Kitchen AbvGr': null,
  'Kitchen Qual': null,
  'TotRms AbvGrd': null,
  'Functional': null,
  'Fireplaces': null,
  'Fireplace Qu': null,
  'Garage Type': null,
  'Garage Yr Blt': null,
  'Garage Finish': null,
  'Garage Cars': null,
  'Garage Area': null,
  'Garage Qual': null,
  'Garage Cond': null,
  'Paved Drive': null,
  'Wood Deck SF': null,
  'Open Porch SF': null,
  'Enclosed Porch': null,
  '3Ssn Porch': null,
  'Screen Porch': null,
  'Pool Area': null,
  'Sale Type': null,
  'Sale Condition': null,
};
