Map<String, Map<String, dynamic>> generalFeatureMap = {
  'MS SubClass': {
    '1-STORY 1946 & NEWER ALL STYLES': 20,
    '2-STORY 1946 & NEWER': 60,
    '1-STORY PUD': 120,
    '1-1/2 STORY FINISHED ALL AGES': 50,
    'SPLIT FOYER': 85,
    '2-STORY PUD': 160,
    'SPLIT OR MULTI-LEVEL': 80,
    '1-STORY 1945 & OLDER': 30,
    '2-STORY 1945 & OLDER': 90,
    '2 FAMILY CONVERSION': 190,
    '1-1/2 STORY UNFINISHED': 45,
    '1-1/2 STORY FINISHED 1945 & OLDER': 70,
    '1-1/2 STORY FINISHED 1946 & NEWER': 75,
    'SPLIT/LEVEL': 40,
    'PUD MULTILEVEL': 180,
    'PUD MULTIFAMILY': 150,
  },
  'MS Zoning': {
    'Residential Low Density (RL)': 'RL',
    'Residential High Density (RH)': 'RH',
    'Floating Village Residential (FV)': 'FV',
    'Residential Medium Density (RM)': 'RM',
    'Commercial (C)': 'C (all)',
    'Industrial (I)': 'I (all)',
    'Agriculture (A)': 'A (agr)',
  },
  'Street': {'Paved': 'Pave', 'Gravel': 'Grvl'},
  'Lot Shape': {
    'Regular': 'Reg',
    'Slightly Irregular': 'IR1',
    'Moderately Irregular': 'IR2',
    'Irregular': 'IR3',
  },
  'Land Contour': {
    'Level': 'Lvl',
    'Hillside': 'HLS',
    'Banked': 'Bnk',
    'Low': 'Low',
  },
  'Utilities': {
    'All Public': 'AllPub',
    'No Sewer': 'NoSewr',
    'No Sewer & Water': 'NoSeWa',
  },
  'Lot Config': {
    'Corner': 'Corner',
    'Inside': 'Inside',
    'Cul-De-Sac': 'CulDSac',
    'Frontage on 2 Sides': 'FR2',
    'Frontage on 3 Sides': 'FR3',
  },
  'Land Slope': {
    'Gentle Slope': 'Gtl',
    'Moderate Slope': 'Mod',
    'Severe Slope': 'Sev',
  },
};
